apiVersion: v2
name: vault
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.14.8"
dependencies:
  - name: vault
    version: 1.20.4
    repository: oci://ghcr.io/bank-vaults/helm-charts
